const data = {
  products: [
    {
      id: 1,
      name: "Free Shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: 2,
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: 3,
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Asos",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: 4,
      name: "Skinny Pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Fited Pants",
    },
    {
      id: 5,
      name: "Dressy Pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: "Work Pants",
    },
    {
      id: 6,
      name: "Classic Pants",
      category: "Pants",
      image: "images/pants3.jpg",
      price: 75,
      brand: "Polo",
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: "Normal Pants",
    },
  ],
};

export default data;
